version: '3.8'
services:
        db:
                image: mysql:latest
                environment:
                        MYSQL_ROOT_PASSWORD: 1
                        MYSQL_DATABASE: db01
                ports:
                        - "3333:3306"
                volumes:
                        - ./db/data:/var/lib/mysql
                        - ./mysql-dump:/docker-entrypoint-initdb.d

        web:
                depends_on:
                       - db
                image: tomcat:9
                environment:
                        MYSQL_ROOT_PASSWORD: 1
                        MYSQL_DATABASE: db01
                ports:
                        - "8080:8080"
                volumes:
                        - ./target/ROOT.war:/usr/local/tomcat/webapps/ROOT.war